In [1]:
import numpy as np

In [3]:
x = np.array([1, 2, 3])

In [4]:
y = np.array([3, 2, 1])

In [5]:
z = np.dot(x, y)

In [6]:
print(z)

10


In [7]:
x = np.matrix([[1, 2, 3, 4], [3, 2, 1, 4], [1, 2, 4, 5], [9, 5, 4, 1]])

In [8]:
x

matrix([[1, 2, 3, 4],
        [3, 2, 1, 4],
        [1, 2, 4, 5],
        [9, 5, 4, 1]])

In [9]:
x.shape

(4, 4)

In [10]:
x = np.matrix([[1, 2, 3], [2, 3, 1], [1, 3, 2]])

In [11]:
x

matrix([[1, 2, 3],
        [2, 3, 1],
        [1, 3, 2]])

In [12]:
y = np.matrix([[2], [1], [3]])

In [13]:
y

matrix([[2],
        [1],
        [3]])

In [14]:
x.shape

(3, 3)

In [15]:
y.shape

(3, 1)

In [16]:
print(x * y)

[[13]
 [10]
 [11]]


In [17]:
from numpy import linalg as LA

In [18]:
x = np.matrix([[1, 2, 3], [2, 1, 3], [3, 1, 2]])

In [19]:
x

matrix([[1, 2, 3],
        [2, 1, 3],
        [3, 1, 2]])

In [20]:
x.shape

(3, 3)

In [21]:
LA.matrix_rank(x)

3