In [1]:
import pandas as pd

In [3]:
data = pd.read_csv('Datas/example_train1.csv')

In [4]:
import sklearn
import numpy as np

In [6]:
data.head()

Document      Class
0         Teclov is a great educational institution.  education
1            Educational greatness depends on ethics  education
2  A story of great ethics and educational greatness  education
3                           Sholey is a great cinema     cinema
4                   good movie depends on good story     cinema

In [7]:
numpy_array = data.as_matrix()
X = numpy_array[:, 0]
Y = numpy_array[:, 1]

C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [8]:
print("X")
print(X)
print("Y")
print(Y)

X
['Teclov is a great educational institution.'
 'Educational greatness depends on ethics'
 'A story of great ethics and educational greatness'
 'Sholey is a great cinema' 'good movie depends on good story']
Y
['education' 'education' 'education' 'cinema' 'cinema']


In [9]:
from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer()

In [10]:
vec.fit(X)
vec.vocabulary_

{'teclov': 15,
 'is': 9,
 'great': 6,
 'educational': 3,
 'institution': 8,
 'greatness': 7,
 'depends': 2,
 'on': 12,
 'ethics': 4,
 'story': 14,
 'of': 11,
 'and': 0,
 'sholey': 13,
 'cinema': 1,
 'good': 5,
 'movie': 10}

In [11]:
vec = CountVectorizer(stop_words = 'english')
vec.fit(X)
vec.vocabulary_

{'teclov': 11,
 'great': 5,
 'educational': 2,
 'institution': 7,
 'greatness': 6,
 'depends': 1,
 'ethics': 3,
 'story': 10,
 'sholey': 9,
 'cinema': 0,
 'good': 4,
 'movie': 8}

In [13]:
print(vec.get_feature_names())
print(len(vec.get_feature_names()))

['cinema', 'depends', 'educational', 'ethics', 'good', 'great', 'greatness', 'institution', 'movie', 'sholey', 'story', 'teclov']
12


In [15]:
X_transformed = vec.transform(X)
X_transformed
print(X_transformed)

  (0, 2)	1
  (0, 5)	1
  (0, 7)	1
  (0, 11)	1
  (1, 1)	1
  (1, 2)	1
  (1, 3)	1
  (1, 6)	1
  (2, 2)	1
  (2, 3)	1
  (2, 5)	1
  (2, 6)	1
  (2, 10)	1
  (3, 0)	1
  (3, 5)	1
  (3, 9)	1
  (4, 1)	1
  (4, 4)	2
  (4, 8)	1
  (4, 10)	1


In [16]:
X_transformed

<5x12 sparse matrix of type '<class 'numpy.int64'>'
	with 20 stored elements in Compressed Sparse Row format>

In [18]:
X = X_transformed.toarray()
X

array([[0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1],
       [0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 1, 0]], dtype=int64)

In [20]:
pd.DataFrame(X, columns = vec.get_feature_names())

cinema  depends  educational  ethics  good  great  greatness  institution  \
0       0        0            1       0     0      1          0            1   
1       0        1            1       1     0      0          1            0   
2       0        0            1       1     0      1          1            0   
3       1        0            0       0     0      1          0            0   
4       0        1            0       0     2      0          0            0   

   movie  sholey  story  teclov  
0      0       0      0       1  
1      0       0      0       0  
2      0       0      1       0  
3      0       1      0       0  
4      1       0      1       0

In [22]:
test_data = pd.read_csv('Datas/example_test.csv')

In [23]:
test_data

Document      Class
0  very good educational institution  education

In [25]:
test_data['Class'] = test_data.Class.map({'cinema' : 0, 'education' : 1})
test_data

Document  Class
0  very good educational institution    NaN

In [27]:
test_numpy_array = test_data.as_matrix()
X_test = test_numpy_array[:, 0]
Y_test = test_numpy_array[:, 1]

C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [29]:
print("X_test")
print(X_test)
print("Y_test")
print(Y_test)

X_test
['very good educational institution']
Y_test
[nan]


In [30]:
X_test_transformed = vec.transform(X_test)
X_test_transformed

<1x12 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [31]:
X_test = X_test_transformed.toarray()
X_test

array([[0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0]], dtype=int64)

In [36]:
# Multinomial Naive Bayes

In [35]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(X, Y)
mnb.predict_proba(X_test)

array([[0.32808399, 0.67191601]])

In [38]:
proba = mnb.predict_proba(X_test)
print("Test data belonging to cinema", proba[:, 0])
print("Test data belonging to education", proba[:, 1])

Test data belonging to cinema [0.32808399]
Test data belonging to education [0.67191601]


In [39]:
pd.DataFrame(proba, columns = ['Cinema', 'Education'])

Cinema  Education
0  0.328084   0.671916

In [40]:
# Bernoulli Naive Bayes

In [41]:
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()
bnb.fit(X, Y)
bnb.predict_proba(X_test)
proba_bnb = bnb.predict_proba(X_test)

In [42]:
pd.DataFrame(proba_bnb, columns = ['Cinema', 'Education'])

Cinema  Education
0  0.232637   0.767363

In [43]:
print("Test belonging to Cinema", proba_bnb[:, 0])
print("Test belonging to education", proba_bnb[:, 1])

Test belonging to Cinema [0.2326374]
Test belonging to education [0.7673626]
