In [1]:
import numpy

In [2]:
numpy.array([1, 2, 3])

array([1, 2, 3])

In [3]:
import numpy as np

In [4]:
x = np.array([1, 2, 3])

In [5]:
x

array([1, 2, 3])

In [6]:
y = np.array([[1, 2], [3, 9]])

In [7]:
y

array([[1, 2],
       [3, 9]])

In [8]:
y.shape

(2, 2)

In [9]:
x

array([1, 2, 3])

In [12]:
y.dtype

dtype('int32')

In [14]:
x.dtype

dtype('int32')

In [15]:
x

array([1, 2, 3])

In [16]:
x.ndim

1

In [17]:
print(type(x))

<class 'numpy.ndarray'>


In [18]:
print(type(y))

<class 'numpy.ndarray'>


In [19]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
c = range(10000)

In [22]:
%timeit [i**3 for i in c]

4.36 ms ± 502 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [26]:
c_numpy = np.arange(10000)

In [27]:
%timeit c_numpy**3

25.9 µs ± 4 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [29]:
x1 = range(10000)
x2 = [i**2 for i in range(10000)]

In [42]:
list(map(lambda x , y : x * y , 1 , 2))

TypeError: 'int' object is not iterable

In [43]:
x1 = np.array(11)
x2 = np.array(12)

In [44]:
%timeit x1 * x2

674 ns ± 88.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [46]:
np.arange(2, 11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
np.arange(2, 12, 2)

array([ 2,  4,  6,  8, 10])

In [49]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [50]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [51]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
np.full((4, 1), 5)

array([[5],
       [5],
       [5],
       [5]])

In [53]:
np.full((4, 4), 2.2, dtype = np.int)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [54]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [55]:
v = np.array([1, 2, 3])

In [56]:
v

array([1, 2, 3])

In [57]:
np.tile(v, (1, 3))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [58]:
np.random.random()

0.942708296493913

In [59]:
11*np.random.random() +50

58.171446837862405

In [60]:
np.random.random([3, 3])

array([[0.14256752, 0.69141641, 0.63024344],
       [0.7628541 , 0.77820197, 0.90694764],
       [0.88468123, 0.11665171, 0.52043785]])