In [1]:
import numpy as np

In [2]:
np.random.random([3, 3])

array([[0.95161638, 0.3875451 , 0.34360948],
       [0.6952977 , 0.80203313, 0.72451966],
       [0.51869328, 0.00628134, 0.38924449]])

In [3]:
x = np.linspace(1, 25, 100)

In [4]:
x

array([ 1.        ,  1.24242424,  1.48484848,  1.72727273,  1.96969697,
        2.21212121,  2.45454545,  2.6969697 ,  2.93939394,  3.18181818,
        3.42424242,  3.66666667,  3.90909091,  4.15151515,  4.39393939,
        4.63636364,  4.87878788,  5.12121212,  5.36363636,  5.60606061,
        5.84848485,  6.09090909,  6.33333333,  6.57575758,  6.81818182,
        7.06060606,  7.3030303 ,  7.54545455,  7.78787879,  8.03030303,
        8.27272727,  8.51515152,  8.75757576,  9.        ,  9.24242424,
        9.48484848,  9.72727273,  9.96969697, 10.21212121, 10.45454545,
       10.6969697 , 10.93939394, 11.18181818, 11.42424242, 11.66666667,
       11.90909091, 12.15151515, 12.39393939, 12.63636364, 12.87878788,
       13.12121212, 13.36363636, 13.60606061, 13.84848485, 14.09090909,
       14.33333333, 14.57575758, 14.81818182, 15.06060606, 15.3030303 ,
       15.54545455, 15.78787879, 16.03030303, 16.27272727, 16.51515152,
       16.75757576, 17.        , 17.24242424, 17.48484848, 17.72

In [6]:
x.itemsize

8

In [7]:
np.arange(18).shape

(18,)

In [9]:
y = np.arange(18).reshape(2,3,3)

In [10]:
y.shape

(2, 3, 3)

In [11]:
np.arange(18).reshape(2,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [12]:
y = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
y[0]

1

In [15]:
y[2]

3

In [16]:
y[[2, 3, 5]]

array([3, 4, 6])

In [17]:
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
y[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [19]:
y[2:5]

array([3, 4, 5])

In [20]:
y[0::2]

array([1, 3, 5, 7, 9])

In [22]:
x = np.array([[1, 2], [3, 9], [4, 8]])

In [23]:
x

array([[1, 2],
       [3, 9],
       [4, 8]])

In [24]:
x[1, 1]

9

In [25]:
x > 1

array([[False,  True],
       [ True,  True],
       [ True,  True]])

In [26]:
x [(x > 2) & (x < 5)]

array([3, 4])

In [27]:
x = np.arange(10)

In [28]:
y = x

In [29]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
y[0] = 1

In [32]:
y

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.shares_memory(x, y)

True

In [34]:
x = np.arange(10)

In [35]:
y = x.copy()

In [36]:
y[0] = 22

In [37]:
y

array([22,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [38]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.shares_memory(x, y)

False

In [40]:
x = np.array([[1, 2, 3], [4, 8, 9]])

In [41]:
x

array([[1, 2, 3],
       [4, 8, 9]])

In [42]:
x.T

array([[1, 4],
       [2, 8],
       [3, 9]])

In [43]:
y = np.array([[1, 2, 3], [3, 2, 1]])

In [44]:
y

array([[1, 2, 3],
       [3, 2, 1]])

In [45]:
x

array([[1, 2, 3],
       [4, 8, 9]])

In [46]:
x == y

array([[ True,  True,  True],
       [False, False, False]])

In [47]:
np.vstack((x, y))

array([[1, 2, 3],
       [4, 8, 9],
       [1, 2, 3],
       [3, 2, 1]])

In [48]:
np.hstack((x, y))

array([[1, 2, 3, 1, 2, 3],
       [4, 8, 9, 3, 2, 1]])

In [49]:
x = np.arange(1, 10)

In [50]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [51]:
np.cos(x)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [52]:
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [53]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.sum(x)

45

In [55]:
np.median(x)

5.0

In [56]:
x.std()

2.581988897471611

In [58]:
x = np.arange(1, 10).reshape(3, 3)

In [59]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
np.linalg.det(x)

-9.51619735392994e-16

In [61]:
np.linalg.inv(x)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [62]:
np.linalg.eig(x)

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [63]:
y = x.T

In [64]:
y

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [65]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
np.dot(x,y)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [67]:
x = np.array([1, 2, 1], dtype=bool)
y = np.array([2, 1, 2], dtype=bool)

In [68]:
np.logical_or(x, y)

array([ True,  True,  True])

In [69]:
np.logical_and(x, y)

array([ True,  True,  True])

In [70]:
np.all(x == x)

True

In [71]:
x.sum()

3

In [73]:
x.sum(axis=0)

3

In [78]:
x.max()

True

In [79]:
x.argmax()

0

In [80]:
x

array([ True,  True,  True])

In [81]:
x

array([ True,  True,  True])

In [82]:
x.shape

(3,)

In [83]:
x = np.arange(10)

In [84]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
x.shape

(10,)

In [86]:
x = np.arange(1, 10)

In [87]:
x.shape

(9,)

In [88]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
x[:, np.newaxis].shape

(9, 1)

In [92]:
np.sort(x)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])